//profile.pdb

CREATE TABLE IF NOT EXISTS TNORME (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	nname VARCHAR(32) NOT NULL, 
	code VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS TFAMILY (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	fname VARCHAR(12) NOT NULL, 
	normeid INTEGER NOT NULL, 
	norme2id INTEGER DEFAULT NULL,
	imageid INTEGER NOT NULL,
	drawerid SMALLINT DEFAULT (0),
	descryption VARCHAR(120) NULL,
	FOREIGN KEY(normeid) REFERENCES TNORME(id)
);

CREATE TABLE IF NOT EXISTS TIMAGE (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	imagedata BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS TPROFILES (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	familyid INTEGER NOT NULL, 
	profilename VARCHAR(32) NOT NULL,
	FOREIGN KEY(familyid) REFERENCES TFAMILY(id)	
);

CREATE TABLE IF NOT EXISTS TNAMES (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	pname VARCHAR(32) DEFAULT NULL, 
	punit VARCHAR(32) DEFAULT NULL,
	descryption VARCHAR(120) NULL
);

CREATE TABLE IF NOT EXISTS TVALUES (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	profileid INTEGER NOT NULL, 
	nameid INTEGER NOT NULL, 
	valuef REAL DEFAULT NULL,
	valuet VARCHAR(32) DEFAULT NULL,
	FOREIGN KEY(profileid) REFERENCES TPROFILES(id), 
	FOREIGN KEY(nameid) REFERENCES TNAMES(id)	
);