INSERT INTO TNORME VALUES(1,"Eurocode","EC");
INSERT INTO TNORME VALUES(2,"German","DIN");
INSERT INTO TNORME VALUES(3,"British","BS");
INSERT INTO TNORME VALUES(4,"American","ASTM");
INSERT INTO TNORME VALUES(5,"Russian","RU");
INSERT INTO TNORME VALUES(6,"Czech","CSN");
INSERT INTO TNORME VALUES(7,"Japanese","Japan");
INSERT INTO TNORME VALUES(8,"China","China");
INSERT INTO TNORME VALUES(9,"Canadische","CSA");
INSERT INTO TNORME VALUES(10,"Indian","IS");

INSERT INTO TFAMILY VALUES(1,"IPE",1,1,1);
INSERT INTO TFAMILY VALUES(2,"HEA",1,2,1);
INSERT INTO TFAMILY VALUES(3,"HEB",1,3,1);
INSERT INTO TFAMILY VALUES(4,"HEM",1,4,1);
INSERT INTO TFAMILY VALUES(5,"HEC",1,4,1);
